"""rename address

Revision ID: 451e8615c6d2
Revises: edfd521f51d7
Create Date: 2024-03-20 23:30:37.203622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451e8615c6d2'
down_revision = 'edfd521f51d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
