"""add Department

Revision ID: 85553b95cfdc
Revises: c3e01eba7747
Create Date: 2024-03-20 23:23:47.098387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85553b95cfdc'
down_revision = 'c3e01eba7747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
